"""Regenerate field/anchors.js from the app's own barangay data (single source of truth).

Run after any change to the barangay table:   python app\\build_field_pwa.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import data_core as dc


def anchors_payload():
    """[{"b": barangay, "lat": ..., "lon": ... or None}] sorted by name, from Layers()."""
    L = dc.Layers()
    by_name = {b["barangay"]: b for b in L.brgy_anchors}
    rows = []
    for name in sorted(L.brgy["barangay"].tolist()):
        a = by_name.get(name, {}).get("anchor")
        rows.append({"b": name, "lat": a["lat"] if a else None,
                     "lon": a["lon"] if a else None})
    return rows


def main():
    rows = anchors_payload()
    out = Path(__file__).resolve().parents[1] / "field" / "anchors.js"
    out.parent.mkdir(exist_ok=True)
    out.write_text(
        "// Generated by app/build_field_pwa.py from data_core.Layers() - do not edit by hand.\n"
        "// Barangay names + OSM anchor points. Data (c) OpenStreetMap contributors, ODbL.\n"
        "window.CS_FIELD = " + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote {out} ({len(rows)} barangays, "
          f"{sum(1 for r in rows if r['lat'] is not None)} anchored)")


if __name__ == "__main__":
    main()
